### PR TITLE
feat(dataclasses): fix dataclasses line 550 contain _ in var typing.C…

### PR DESCRIPTION
**Pull request by angie8215**
…lassVar

### CODE REVIEW

**Comment by ericvsmith** [comment]
What version of Python is this for?

This is a backport of dataclasses to Python 3.6, which is no longer maintained. Please let me know your use case, and if you're testing with 3.6.

**Comment by angie8215** [comment]
I am migrating my project to version 3.10 of python, but for some reason
one of the libraries I have is requiring dataclasses and when compiling I
get an error specifically on that line 550 for the underscore.
Would you have the possibility to modify that detail?

**Comment by ericvsmith** [comment]
This code can only be used in python 3.6.

**Comment by angie8215** [comment]
Is it possible for you to remove the underscore on line 550?

**Comment by ericvsmith** [comment]
Why?

**Pull request closed without merging**
