### PR TITLE
Merge changes from bpo-33796 and bpo-33805

### PR DESCRIPTION
**Pull request by noamkush**
See [python/cpython#7488](https://github.com/python/cpython/pull/7488) and [python/cpython#7580](https://github.com/python/cpython/pull/7580)
This fixes some bugs in replace.

### CODE REVIEW

**Comment by nbraud** [comment]
Closes #143

**Comment by nbraud** [comment]
@ericvsmith Please consider merging this and making a patch release.

Those bugs are a severe problem for `dataclasses` users.

**Comment by hoogamaphone** [comment]
I am eagerly awaiting these bug fixes.

**Comment by danigosa** [comment]
+1

**Comment by rpavlik** [comment]
It looks like this is not yet on pypi? I'm still back on 0.6 there.

**Comment by ericvsmith** [comment]
Is it not in the 0,8 that's on PyPI?

**Comment by rpavlik** [comment]
Oh, strange. It must have been some caching thing locally, that it was installing 0.6 instead of 0.8. Sorry for the noise.

**Pull request merged**
