### PR TITLE
Update dataclasses.py

### PR DESCRIPTION
**Pull request by angie8215**
Change is made at line 550, the underscore is removed.

### CODE REVIEW

**Comment by ericvsmith** [comment]
Why? What problem is being solved?

This code only targets python 3.6, and is generally unmaintained.

**Comment by angie8215** [comment]
I get an error on line 550 because of the underscore: typing._ClassVar,
when I removed it my project works correctly.

**Comment by ericvsmith** [comment]
Please follow advice like https://clickup.com/blog/how-to-write-a-bug-report/ on how to file a good bug report. You have not provided nearly enough information for anyone to help you.

**Comment by angie8215** [comment]
My job is to implement CI/CD with gitlab and automate unit tests. Buildout
for Odoo is being used. When installing the required libraries, it asks me
for dataclasses version 0.8. However, when running the unit tests with
green, I get the following error:
[image: image.png]
By directly removing that underscore from the library's dataclasses.py
file, my project runs without problem.

**Comment by ericvsmith** [comment]
You still have not provided enough information for anyone to reproduce your issue. I'm going to close this.

**Pull request closed without merging**
